In [1]:
print("hello world")

hello world


In [2]:
#Python Libray for array
import numpy as np

In [3]:
mylist = [1,2,3]
type(mylist)

list

In [5]:
#List to an array
myarray = np.array(mylist)

In [6]:
myarray

array([1, 2, 3])

In [7]:
#Datatype of array
type(myarray)

numpy.ndarray

In [9]:
# Print an array by gaps in index
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
# 2d array row,column
# np.zero create an array of zero datatype float
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# np.zero create an array of ones datatype float
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
#fixed random number generation using seed
np.random.seed(101)
# create 0 to 100 number and give 10 numbers
array = np.random.randint(0,100,10)
print(array)

[95 11 81 70 63 87 75  9 77 40]


In [15]:
array2= np.random.randint(0,100,10)
array2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [21]:
#maximum element in array
array.max()

95

In [25]:
#minimum element in array
array2.min()

4

In [17]:
#maximum element index in array
array.argmax()

0

In [24]:
#minimum element index in array2
array2.argmin()

0

In [26]:
array.mean()

60.8

In [ ]:
#Reshape an 1d array into 2d array

In [30]:
#as 2*5 = 10 elements in 1d array
array.reshape((2,5))
#or
array.reshape((5,2))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [38]:
matric = np.arange(0,100).reshape((10,10))

In [39]:
matric

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [40]:
 row = 0 
 col = 1

In [45]:
matric[4,6]

46

In [47]:
# data slicing
# get the every values of first column
matric[:,1].reshape((10,1))

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [49]:
# get the every values of 3rd row
matric[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [50]:
#specific area of a matrix
# Get all the rows from 0 to 3 and ll the columns from  2 and 6
matric[0:3,2:6]

array([[ 2,  3,  4,  5],
       [12, 13, 14, 15],
       [22, 23, 24, 25]])

In [51]:
#resign the value of that specific chunk
matric[0:3,2:6] = 0
matric

array([[ 0,  1,  0,  0,  0,  0,  6,  7,  8,  9],
       [10, 11,  0,  0,  0,  0, 16, 17, 18, 19],
       [20, 21,  0,  0,  0,  0, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [52]:
#Copy of the matrix
mynewmat= matric.copy()


In [57]:
mynewmat[0:5,0:10] = 1
mynewmat

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])